services:
  db:
    image: library/postgres:15
    restart: ${DOCKER_RESTART}
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    networks:
      - fakturomat-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "25m" # file size

  web_php:
    build:
      context: .
      dockerfile: docker/web_php/Dockerfile
    restart: ${DOCKER_RESTART}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: db #override env
    networks:
      - fakturomat-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "25m" # file size

  caddy:
    image: caddy:2.7
    restart: ${DOCKER_RESTART}
    working_dir: /var/www
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    depends_on:
      - web_php
    networks:
      - caddy
      - fakturomat-net
    labels:
      caddy: ${APP_URL}
      caddy.reverse_proxy: "{{upstreams}}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "25m" # file size

volumes:
  postgres:

networks:
  fakturomat-net:
  caddy:
    external: true
