version: '3.9'

services:
  db:
    image: library/postgres:15
    restart: ${DOCKER_RESTART}
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - fakturomat-net

  web_php:
    build:
      context: .
      dockerfile: docker/web_php/Dockerfile
      args:
        - DOCKER_WORK_DIR=${DOCKER_WORK_DIR}
    restart: ${DOCKER_RESTART}
    working_dir: ${DOCKER_WORK_DIR}
    volumes:
      - ./:${DOCKER_WORK_DIR}
    environment:
      DB_HOST: db #override env
    networks:
      - fakturomat-net

  caddy:
    image: caddy:2.7
    restart: ${DOCKER_RESTART}
    working_dir: ${DOCKER_WORK_DIR}
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    depends_on:
      - web_php
    networks:
      - caddy
      - fakturomat-net
    labels:
      caddy: ${APP_URL}
      caddy.reverse_proxy: "{{upstreams}}"

volumes:
  postgres:

networks:
  fakturomat-net:
  caddy:
    external: true
