version: '3'

services:
  db:
    image: library/postgres:13
    restart: ${DOCKER_RESTART}
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - default

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - DOCKER_WORK_DIR=${DOCKER_WORK_DIR}
    restart: ${DOCKER_RESTART}
    working_dir: ${DOCKER_WORK_DIR}
    volumes:
      - ./:${DOCKER_WORK_DIR}
    environment:
      DB_HOST: db #override env
    networks:
      - default

  nginx:
    image: library/nginx:1.18
    restart: ${DOCKER_RESTART}
    working_dir: ${DOCKER_WORK_DIR}
    volumes:
      - ./:/app:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:${DOCKER_WORK_DIR}
    depends_on:
      - web
    networks:
      - default
    environment:
      - VIRTUAL_HOST=${WEBPAGE_DOMAIN}

volumes:
  postgres:

networks:
  default:
    external:
      name: gateway
