version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - default
      - fakturomat

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        - DOCKER_WORK_DIR=${DOCKER_WORK_DIR}
    working_dir: ${DOCKER_WORK_DIR}
    volumes:
      - ./:${DOCKER_WORK_DIR}
    environment:
      DB_HOST: db
    networks:
      - fakturomat

  nginx:
    image: nginx:1.17
    working_dir: ${DOCKER_WORK_DIR}
    volumes:
      - ./:/app:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:${DOCKER_WORK_DIR}
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fakturomat.rule=Host(`${WEBPAGE_DOMAIN}`)"
      - "traefik.http.routers.fakturomat.entryPoints=web"
      - "traefik.http.middlewares.fakturomat-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.routers.fakturomat.middlewares=fakturomat-https-redirect"

      - "traefik.http.routers.fakturomat-secure.rule=Host(`${WEBPAGE_DOMAIN}`)"
      - "traefik.http.routers.fakturomat-secure.entryPoints=websecure"
      - "traefik.http.routers.fakturomat-secure.tls=true"
      - "traefik.http.routers.fakturomat-secure.service=fakturomat"
      - "traefik.http.services.fakturomat.loadbalancer.server.port=80"
      - "traefik.http.routers.fakturomat.tls.certresolver=myresolver"
    networks:
      - default
      - fakturomat
#    ports:
#      - 80:80

volumes:
  postgres:

networks:
  default:
    external:
      name: gateway

  fakturomat:
    internal: true