name: Laravel

on: [push]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Npm install and build
      run: |
        npm ci --prefer-offline --no-audit
        mkdir -p public/fonts && cp node_modules/font-awesome/fonts/* public/fonts
        npm run development -- --no-progress

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
